### ISSUE TITLE
在linux 下，工具內GUIcfg.txt 找不到

### ISSUE THREAD

**Issue by skysumbra** [affggh/Magisk_patcher#1]
在linux 上執行出現以下錯誤
python3 MagiskPatcher.py 
```
Traceback (most recent call last):
  File "/home/AAA/Videos/Magisk_patcher-main/MagiskPatcher.py", line 456, in <module>
    main()
  File "/home/AAA/Videos/Magisk_patcher-main/MagiskPatcher.py", line 26, in main
    with open(configPath, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/AAA/Videos/Magisk_patcher-main/bin\\GUIcfg.txt'
```
推測需要檔案的路徑沒有相容linux ，斜線反的未支援
python3 版本是3.9

**Comment by affggh** [comment]
> 

实际上还没有对linux支持的计划，这个程序基本上都是给Windows写的，这个程序主要核心是批处理写的程序。不过既然你问了我觉得近期可能会尽量添加对linux的支持😊，因为一直很少有人提issue我就以为没人用来着。

**Comment by affggh** [comment]
> 在linux 上執行出現以下錯誤 python3 MagiskPatcher.py
> 
> ```
> Traceback (most recent call last):
>   File "/home/AAA/Videos/Magisk_patcher-main/MagiskPatcher.py", line 456, in <module>
>     main()
>   File "/home/AAA/Videos/Magisk_patcher-main/MagiskPatcher.py", line 26, in main
>     with open(configPath, "r") as file:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/AAA/Videos/Magisk_patcher-main/bin\\GUIcfg.txt'
> ```
> 
> 推測需要檔案的路徑沒有相容linux ，斜線反的未支援 python3 版本是3.9

好消息，现在支持linux上面进行修补了
