### ISSUE TITLE
正解

### ISSUE THREAD

**Issue by xxroot** [affggh/Magisk_patcher#14]
正解

_Originally posted by @affggh in https://github.com/affggh/Magisk_patcher/issues/13#issuecomment-1585535603_
            我在研究VIVO的ROOT,修补后，刷入就不开机，加个联系方式讨论一下可以吗？

**Comment by affggh** [comment]
你可以试试wuxianlin改的那个https://github.com/wuxianlin/build_magisk_vivo/tree/master

**Comment by xxroot** [comment]
好，我试试
&nbsp;


智酷网
***@***.***



&nbsp;
