### ISSUE TITLE
possible to add  English

### ISSUE THREAD

**Issue by NoRRt** [affggh/Magisk_patcher#16]
Hello, is it possible to add English to the program?

**Comment by affggh** [comment]
Sure, I already add en_US language in commit https://github.com/affggh/Magisk_patcher/commit/24c9ee041a6778edd067e67ccd3e327edb4df80b

**Comment by affggh** [comment]
![image](https://github.com/affggh/Magisk_patcher/assets/46290091/21bbeb26-70a0-42da-b873-433ae35ab168)
it looks like this on windows

**Comment by NoRRt** [comment]
Tnx
