### ISSUE TITLE
Feature Request - Make This Program Accessible From The Command Line

### ISSUE THREAD

**Issue by TheRealMrWicked** [affggh/Magisk_patcher#19]
Hello I am currently working on a command line program that is meant to fully automate the downloading, rooting and flashing of certain Android phones (Samsung and Pixels).

This program is the only one of it's kind, that allows for patching of files using magisk on Windows.

Do you think it would be possible to make the program work over the command line.

Thank you in Advance

**Comment by affggh** [comment]
its easy to do, i will consider.

**Comment by RealMrWicked** [comment]
Okay thank you, much appreciated.
