### ISSUE TITLE
建議需要的module 沒有則自動安裝

### ISSUE THREAD

**Issue by skysumbra** [affggh/Magisk_patcher#2]
建議需要的module 沒有則自動安裝
```
./MagiskPatcher.py 
Traceback (most recent call last):
  File "/home/AAA/Magisk_patcher-20220611/./MagiskPatcher.py", line 14, in <module>
    from mttkinter import mtTkinter as tk 
ModuleNotFoundError: No module named 'mttkinter'
```

**Comment by affggh** [comment]
可以

**Comment by fumofu3994** [comment]
以后会补全的

**Comment by affggh** [comment]
> 建議需要的module 沒有則自動安裝
> 
> ```
> ./MagiskPatcher.py 
> Traceback (most recent call last):
>   File "/home/AAA/Magisk_patcher-20220611/./MagiskPatcher.py", line 14, in <module>
>     from mttkinter import mtTkinter as tk 
> ModuleNotFoundError: No module named 'mttkinter'
> ```

重置之后补上了，感谢反馈
https://github.com/affggh/Magisk_patcher/blob/ab48bcea585cfd99ccb709fb5a832b53d6b7dd58/Magiskpatcher.py#L16-#L26
