### ISSUE TITLE
win10 64位环境 修补时报错

### ISSUE THREAD

**Issue by HToken** [affggh/Magisk_patcher#6]
AttributeError: 'myStdout' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'myStdout' object has no attribute 'flush'

**Comment by affggh** [comment]
> AttributeError: 'myStdout' object has no attribute 'flush' Exception ignored in sys.unraisablehook: AttributeError: 'myStdout' object has no attribute 'flush'

cause my stdout doesnt have flush method ,that is not a big issue, you can just download magisk from github and put it into prebuilt folder, the program can auto detect apk file in prebuilt dir, this is network or mirror website is missing

**Comment by affggh** [comment]
我弱智了，我还拿英语回，这是下载有问题，可以改镜像在其它那个页面，或者你自己下好一个magisk的apk放进prebuilt目录里

**Comment by HToken** [comment]
> 我弱智了，我还拿英语回，这是下载有问题，可以改镜像在其它那个页面，或者你自己下好一个magisk的apk放进prebuilt目录里

haha，英语也能看懂。感谢解答，工具很好用
